export const CDN_PREFIX = "https://res.cloudinary.com/djkjakggs/image/upload/";
export const partner = [
  {
    logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/kukufm_htbrgn.svg`,
    alt: "kukufm-logo",
    title: "kukufm-logo",
    growth: "400%",
    desc: "Revenue increase",
    url: "/case-study/kukufm",
    className: "h-[28px] w-[95px]",
    // height: {28},
    // width: "95px",
  },
  {
    logo: "/saleshandy.svg",
    alt: "saleshandy",
    title: "saleshandy",
    growth: "4X",
    desc: "Time-to-market speed",
    url: "/case-study",
    className: "h-[23px] w-[140px]",
  },
  {
    logo: "/betterbugs.svg",
    alt: "betterbugs",
    title: "betterbugs",
    growth: "70%",
    desc: "User registrations",
    url: "/case-study/betterbugs",
    className: "h-[23px] w-[141px]",
  },
  {
    logo: "/obatala-coffee.svg",
    alt: "obatala-coffee",
    title: "obatala-coffee",
    growth: "90%",
    desc: "Ecommerce Growth",
    url: "/case-study/",
    className: "h-[26px] w-[140px]",
  },
];

export const serviceMenu = [
  {
    url: "/services/conversion-rate-optimization",
    slug: "cro",
    title: "Conversion Rate Optimization",
    des: "Turn traffic into gold with our expert CRO services",
  },
  {
    url: "/services/ecommerce-development",
    title: "E-commerce Development",
    slug: "e-commerce",
    des: "Re-kindle experience for your customers with our proven E-commerce expertise",
  },
  {
    url: "/services/build-my-team",
    slug: "build-agile-team",
    title: "Build your Agile Team",
    des: "Create your dream team with our dedicated Agile professionals",
  },
  {
    url: "/services/mvp",
    slug: "mvp-dev",
    title: "MVP Development",
    des: "Pave your way towards success with our world-class MVP development services",
  },
  {
    url: "/services/saas",
    slug: "saas-dev",
    title: "SaaS Development",
    des: "Get the best SaaS solutions and strike a chord with your users in less time",
  },
];

export const clientLogo = [
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/bvb-media_qoursq.svg`,
      alt: "bvb-media-logo",
      height: 28,
      width: 85,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/hafnia_c81tiy.svg`,
      alt: "hafnia-logo",
      height: 28,
      width: 123,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/sparrow_vd9jqi.svg`,
      alt: "sparrow-logo",
      height: 34,
      width: 98,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/univia_hqz9fq.svg`,
      alt: "univia-logo",
      height: 28,
      width: 108,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/my-pa-box_m84tmp.svg`,
      alt: "my-pa-box-logo",
      height: 28,
      width: 123,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/capermint_ytr6y1.png`,
      alt: "capermint-logo",
      height: 19,
      width: 127,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/kukufm_htbrgn.svg`,
      alt: "kukufm-logo",
      height: 28,
      width: 94,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/healtho_zp3a4i.svg`,
      alt: "healtho-logo",
      height: 34,
      width: 75,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/DMAK_fgvrew.svg`,
      alt: "dmak-logo",
      height: 24,
      width: 65,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/NMACC_immciz.svg`,
      alt: "nmacc-logo",
      height: 44,
      width: 155,
      className: "invert-[0.5]",
  },
  {
      logo: `${CDN_PREFIX}v1703489997/linearloop/client-logo/nurasoi_vqi2ex.svg`,
      alt: "nurasoi-logo",
      height: 34,
      width: 85,
      className: "invert-[0.5]",
  },
  // {
  //     logo: "/client-logo/obatala-coffee.svg",
  //     alt: "obatala-coffee-logo",
  //     height: 26,
  //     width: 137,
  //     className: "invert-[0.5]",
  // },
  // {
  //     logo: "/client-logo/responser.svg",
  //     alt: "responser-logo",
  //     height: 28,
  //     width: 128,
  //     className: "invert-[0.3]",
  // },
  // {
  //     logo: "/client-logo/drive-buddy.png",
  //     alt: "drive-buddy-logo",
  //     height: 20,
  //     width: 80,
  //     className: "invert-[0.5]",
  // },
  // {
  //     logo: "/client-logo/beatroute.png",
  //     alt: "beatroute-logo",
  //     height: 50,
  //     width: 120,
  //     className: "invert-[0.5]",
  // },
  // {
  //     logo: "/client-logo/innovage-logo.svg",
  //     alt: "innovage-logo",
  //     height: 28,
  //     width: 97,
  //     className: "invert-[0.5]",
  // },
];